theme: jekyll-theme-cayman
Title: Welcome to Lizzie Mayes's Homepage! 
description: feel free to bookmark this to keep an eye on my project updates

Header: The dataset I chose that interests me is the NOAA Climactic Dataset found on the NOAA National Centers for Environmental Information website. The potential uses for the datasets are weather and climate data taken from marine, land-based and weather balloon collection that can be used in modeling predictions for climate change, or as environmental variables in ecological studies (such as temperature affects on species ranges).   The link to the site is: [NOAA Climate Data](https://www.ncdc.noaa.gov/data-access). 
